### ISSUE TITLE
Schedule weekly test runs against unfrozen dependencies

### ISSUE THREAD

**Issue by consideRatio** [robots-from-jupyter/robotframework-jupyterlibrary#80]
With tests scheduled to run regularly against dependencies that aren't frozen, we could detect issues arising over time due to changes in dependencies or the various execution environments, such as the GitHub actions runners having certain python unrelated dependencies such as versions of geckodriver etc.

Below is an example of triggers for a github actions test workflow that could be used.

```yaml
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "contrib/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "contrib/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  schedule:
    # At 05:00 on Monday - https://crontab.guru
    - cron: "0 5 * * 1"
  workflow_dispatch:
```
